name: Build container image

on:
  push:
#     branches:
#       - master
  pull_request:

jobs:

  hpccm:
    name: Generate container recipes
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Build hpccm container
      run: docker build . -f .github/workflows/Dockerfile.hpccm -t hpccm
      
    - name: Generate docker recipe
      run: docker run -v `pwd`:/volume hpccm --recipe /volume/megadock_hpccm.py --format docker > Dockerfile
    
    - name: Generate singularity recipe
      run: docker run -v `pwd`:/volume hpccm --recipe /volume/megadock_hpccm.py --format singularity > singularity.def
    
    - name: Upload docker recipe
      uses: actions/upload-artifact@v1
      with:
        name: recipe
        path: Dockerfile

    - name: Upload singularity recipe
      uses: actions/upload-artifact@v1
      with:
        name: recipe
        path: singularity.def


  build-docker:
    needs: [hpccm]
    name: Build docker image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Download generated recipe
      uses: actions/download-artifact@v1
      with:
        name: recipe

    - name: Check artifact
      run: ls recipe

    - name: Build docker image
      run: docker build . -f recipe/Dockerfile -t megadock:hpccm
      
    - name: Check ompi_info
      run: docker run megadock:hpccm ompi_info
      
    - name: Check binary
      run: docker run megadock:hpccm which /workspace/megadock-gpu-dp


  build-singularity:
    needs: [hpccm]
    name: Build singularity image
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Download generated recipe
      uses: actions/download-artifact@v1
      with:
        name: recipe

    - name: Check artifact
      run: ls recipe

    - name: Build docker container for singularity
      run: docker build . -f .github/workflows/Dockerfile.singularity -t singularity

    - name: Build docker image for singularity
      run: docker run --privileged -v `pwd`:/volume singularity --verbose build /volume/singularity.sif /volume/recipe/singularity.def
      
    - name: Check binary
      run: docker run --privileged -v `pwd`:/volume -v /etc/localtime singularity --verbose exec /volume/singularity.sif which /workspace/megadock-gpu-dp
      
    - name: Check ompi_info
      run: docker run --privileged -v `pwd`:/volume -v /etc/localtime singularity --verbose exec /volume/singularity.sif ompi_info
